### ISSUE TITLE
could I use this package for inline on-the-fly keboard?

### ISSUE THREAD

**Issue by mrmrn** [halaei/telegram-bot#2]
hi.
I want to show data to user by some inline keyboard like [this](https://core.telegram.org/file/811140217/1/NkRCCLeQZVc/17a804837802700ea4) 
does this repo support it?

**Comment by halaei** [comment]
Yes. Just pass the appropriate array according to the [bot api docs](https://core.telegram.org/bots/api#sendmessage) into your desired method, e.g. sendMessage. I think something like this will work:

```php
$api->sendMessage([
    'chat_id' => ...,
    'text' => '...',
    'reply_markup' => json_encode(['inline_keyboard' => [
        [['text' => '...', 'url' => '...'], ['text' => '...', 'callback_data' => '...']],//first row
        [...],//second row
    ]),
]);
```
